export default {
  employeeTable: {
    selected: [],
    search: "",
    headers: [
      {
        text: "Ramal",
        align: "start",
        sortable: true,
        value: "ramal",
      },
      { text: "Grupo", value: "grupo" },
      { text: "Gravação", value: "gravacao" },
      { text: "Ações", value: "icon" },
    ],
    employee: [
      {
        ramal: "1001",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1002",
        grupo: "Grupo 2",
        gravacao: "Não",
        icon: "",
        select: false,
      },
      {
        ramal: "1003",
        grupo: "Grupo 1",
        gravacao: "Não",
        icon: "",
        select: false,
      },
      {
        ramal: "1004",
        grupo: "Grupo 3",
        gravacao: "Não",
        icon: "",
        select: false,
      },
      {
        ramal: "1005",
        grupo: "Grupo 2",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1006",
        grupo: "Grupo 1",
        gravacao: "Não",
        icon: "",
        select: false,
      },
      {
        ramal: "1007",
        grupo: "Grupo 5",
        gravacao: "Não",
        icon: "",
        select: false,
      },
      {
        ramal: "1008",
        grupo: "Grupo 5",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1009",
        grupo: "Grupo 2",
        gravacao: "Não",
        icon: "",
        select: false,
      },
      {
        ramal: "1010",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1011",
        grupo: "Grupo 7",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1012",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1013",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1014",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1015",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1016",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1017",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
      {
        ramal: "1018",
        grupo: "Grupo 1",
        gravacao: "Sim",
        icon: "",
        select: false,
      },
    ],
  },
};
