export default {
  employeeTable: {
    headers: [
      { text: "Tipo", value: "tipo" },
      { text: "Quantidade", value: "qt" },
      { text: "Tempo Total", value: "treal" },
      { text: "Tempo de Toque", value: "ttoque" },
      { text: "Tempo de Conversação", value: "tconversa" },
      { text: "Custo", value: "custo" },
    ],
    ramais: ["1000", "1001", "1002", "1003"],
    centro: ["comercial", "rh", "suporte", "comercial"],
    status: ["atendida", "não atendida", "falhou", "ocupado"],
    tipo: ["DDD Fixo", "DDD Local", "DDD Celular", "DDD Loga Distância"],
    data: [
      "Hoje",
      "Ontem",
      "Semana Atual",
      "Semana Anterior",
      "Mês Atual",
      "Mês Anterior",
    ],
    agrupar: ["Ramal", "Centro de Custo", "Origem/Destino", "Status"],

    hora: [
      "1:00",
      "2:00",
      "3:00",
      "4:00",
      "6:00",
      "7:00",
      "8:00",
      "8:00",
      "10:00",
      "11:00",
      "12:00",
    ],
    direcao: ["Interna", "Entrada", "Saída"],
    employee: [
      {
        tipo: "Interna",
        qt: "1",
        treal: "00:00:00",
        ttoque: "00:00:00",
        tconversa: "01:30",
        custo: "R$ 0,00",
        select: false,
      },
      {
        tipo: "Interna",
        qt: "1",
        treal: "00:00:00",
        ttoque: "00:00:00",
        tconversa: "01:30",
        custo: "R$ 0,00",
        select: false,
      },
      {
        tipo: "Interna",
        qt: "1",
        treal: "00:00:00",
        ttoque: "00:00:00",
        tconversa: "01:30",
        custo: "R$ 0,00",
        select: false,
      },
      {
        tipo: "Interna",
        qt: "1",
        treal: "00:00:00",
        ttoque: "00:00:00",
        tconversa: "01:30",
        custo: "R$ 0,00",
        select: false,
      },
      {
        tipo: "Interna",
        qt: "1",
        treal: "00:00:00",
        ttoque: "00:00:00",
        tconversa: "01:30",
        custo: "R$ 0,00",
        select: false,
      },
    ],
  },
};
